POST  http://localhost:3001/api/events
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGVwZSIsInVzZXJuYW1lIjoia2FrYWthIiwiaWQiOiI2MTExYjg0NWNkNmMxNTIxMTA2ZTAzOGQiLCJpYXQiOjE2Mjg1NTEyODQsImV4cCI6MTYyOTE1NjA4NH0.SzL-0em5h1oDiHy0X5SeqmdT-UEZW3O731p79c2jls4

{  
  "title"       : "codigo refactorizado1",
  "description" : "usuario 2 ",
  "highlight"   : true,
  "imgUrl"      : "pepepepepe",
  "dates"       : {
    "date"      : "December 21, 2000 03:24:00",
    "price"     :1555555
  },
  "location"    : "Puerto ballarta",
  "user"        : "6111b845cd6c1521106e038d"
}
