POST  http://localhost:3001/api/events
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmVybmFuZG8iLCJ1c2VybmFtZSI6IkZlcmNvZGUiLCJpZCI6IjYxMTczY2IzZDI1NDNkMDE3ODdjNDQ5NyIsImlhdCI6MTYyODkxMjg0MSwiZXhwIjoxNjI5NTE3NjQxfQ.bUfGYyb-fepz6c9NGLAMfdwbJ3IBvXfsA69LFaJmNNg

{  
  "title"       : "evento relacionado sin guardaraaa",
  "description" : "despues de muchas pruebas y errores",
  "highlight"   : true,
  "imgUrl"      : "www.ijalopa.com",
  "dates"       : {
    "date"      : "December 21, 2000 03:24:00",
    "price"     :1555555
  },
  "location"    : "Puerto jalopa",
  "user"        : "61173cb3d2543d01787c4497"
}
