DELETE http://localhost:3001/api/events/61119071b1d5e42590a0b0d4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmVybmFuZG8iLCJ1c2VybmFtZSI6IkZlcm1hbiIsImlkIjoiNjExMzRhMWY1ODk5NGQxMmIwZDc1NWU3IiwiaWF0IjoxNjI4ODUzOTE3LCJleHAiOjE2Mjk0NTg3MTd9.x5bsbgedXYO_MUhD9Qym3G4w5d-7UGGes-8MWlMVYRA
