PATCH  http://localhost:3001/api/events/610c6c73f266931c204905db
Content-Type:  application/json

{
    "title":"hola FEasdljkdasjklasdjkl",
    "highlight": false,
    "description":"hola soy una nota actualizada",
    "imgUrl":"www.falopaactualizada.com",
    "location":"falopalandia"
}