DELETE http://localhost:3001/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGVwZSIsInVzZXJuYW1lIjoia2FrYWthIiwiaWQiOiI2MTExYjg0NWNkNmMxNTIxMTA2ZTAzOGQiLCJpYXQiOjE2Mjg2MzQwNjksImV4cCI6MTYyOTIzODg2OX0.urcY0j4jy6Sd1wE4jg9xsBiAzz_0l-SAtV3UZ5NmAyg
